#!/bin/sh
set -e

echo "Authenticating and cloning $GIT_URL..."
AUTH_URL=$(echo "$GIT_URL" | sed "s#https://#https://$GIT_USER:$GIT_TOKEN@#")
git clone --branch "$GIT_BRANCH" "$AUTH_URL" /app/src

cd /app/src

echo "Installing dependencies..."
npm install

echo "Building..."
npm run build

echo "Deploying with ENV=$DEPLOY_ENV..."
npm run deploy
